// examples/market/src/vue/Market.vue
<template>
  <div>
    <h1>Vue 购物车</h1>
    <table>
      <thead>
        <tr>
          <th>
            <label> <input type="checkbox" v-model="allChecked" />全选 </label>
          </th>
          <th>商品名称</th>
          <th>商品单价</th>
          <th>购买数量</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="item of itemList" :key="item.id">
          <td>
            <input type="checkbox" v-model="item.checked" />
          </td>
          <td>{{ item.name }}</td>
          <td>{{ item.price }}元</td>
          <td>
            <button @click="item.count--" :disabled="item.count === 0">-</button>
            <b style="margin: 0 4px;">{{ item.count }}</b>
            <button @click="item.count++">+</button>
          </td>
          <td>
            <button @click="removeItem(item)">移除</button>
          </td>
        </tr>
      </tbody>
    </table>
    <h3>总价：{{ totalPrice }} 元</h3>
  </div>
</template>

<script>
import { ItemList } from './store';
export default {
  data() {
    return {
      itemList: ItemList,
    };
  },
  methods: {
    removeItem(item) {
      this.itemList.splice(this.itemList.indexOf(item), 1);
    },
  },
  computed: {
    totalPrice() {
      return this.itemList.filter(i => i.checked).reduce((prev, cur) => prev + cur.count * cur.price, 0);
    },
    allChecked: {
      get() {
        return this.itemList.every(i => i.checked);
      },
      set(val) {
        this.itemList.forEach(item => (item.checked = val));
      },
    },
  },
};
</script>

// examples/market/src/hamburger-react/Market.js
import { Button, HStack, VStack, Text, Input, Table, TableRow, listen } from 'hamburger-js';
import { ItemList } from './store';
import { useState } from 'react';
import _ from 'lodash';

function Counter(item, setItemCount) {
  return HStack(
    Button('-')
      .onClick(() => setItemCount(item.count - 1))
      .disabled(item.count === 0),
    Text(` ${item.count} `).tag('b').margin({ horizontal: 4 }),
    Button('+').onClick(() => setItemCount(item.count + 1))
  );
}

function Checkbox(value, onToggle, label) {
  if (label)
    return Input(value, 'checkbox')
      .wrapLabel(label)
      .onClick(() => onToggle(!value));
  return Input(value, 'checkbox').onClick(() => onToggle(!value));
}

function Market() {
  const [items, setItems] = useState(ItemList);
  const totalPrice = items.filter((i) => i.checked).reduce((prev, cur) => prev + cur.count * cur.price, 0);
  const allChecked = items.every((i) => i.checked);
  function checkAll(val) {
    setItems(items.map((i) => ({ ...i, checked: val })));
  }

  function toggleItem(item, val) {
    const _items = _.cloneDeep(items);
    _items.forEach((i) => {
      if (i.id === item.id) {
        i.checked = val;
      }
    });
    setItems(_items);
  }

  function setItemCount(item, val) {
    setItems(
      items.map((i) => ({
        ...i,
        count: item.id === i.id ? val : i.count,
      }))
    );
  }

  function removeItem(item) {
    setItems(items.filter((i) => i !== item));
  }
  return VStack(
    Text('Hamburger-React 购物车').tag('h1'),
    Table(
      TableRow(Checkbox(allChecked, checkAll, '全选'), '商品名称', '商品单价', '购买数量', '操作'),
      items.map((item) =>
        TableRow(
          Checkbox(item.checked, (val) => toggleItem(item, val)),
          item.name,
          item.price,
          Counter(item, (val) => setItemCount(item, val)),
          Button('移除').onClick(() => removeItem(item))
        ).opacity(0.5, !item.checked)
      )
    ),
    Text(`总价：${totalPrice} 元`).tag('h3')
  ).build();
}

export default Market;
